### ISSUE TITLE
Add functionality to get "duet" videos as well.

### ISSUE THREAD

**Issue by MadsHogenhaug** [Marcus-Friis/thesis#2]
Since TikTok stitches can't be stitched again, we're unable to create an extended video graph using this feature. This means we can't build a long chain of connections through stitches alone. However, using duets might provide a solution. Duets allow for the construction of longer video graphs because you can create a network where a duet can respond to both another duet and a stitch. This creates a more intricate and extended graph, as opposed to stitches, which can’t connect to other stitches (you cannot stitch a stitch). Thus, by leveraging duets, we can develop a more complex and extended network of interactions.

**Comment by Marcus-Friis** [comment]
Done! We won't use duets but it is there for fun :)
