### ISSUE TITLE
Implement *Equicentrality* and *Network Centralization* metrics

### ISSUE THREAD

**Issue by Marcus-Friis** [Marcus-Friis/thesis#6]
igraph in Python does not support these metrics. We should implement them ourselves for comparison of stitch networks.
igraph in R supports it: read more [here](https://r.igraph.org/reference/centralize.html).
[This paper](https://www.sciencedirect.com/science/article/pii/S0378873307000561?casa_token=QeSxNNsbsAsAAAAA:hFK-7cScGDstxnbzO2bByj82zsnfleoiIEfKJ_KB9rNY8pJxcVcqqpjNc1IzirgehNBNz78dIw) also further describes the specifics of various centrality metrics.

**Comment by MadsHogenhaug** [comment]
mail til marcus
